version: '3.3'

services:
  mysql:
    image: mysql:8.0.18
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: pymatcha
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    env_file:
      - .env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - mysql-net
    healthcheck:
      test: "/usr/bin/mysql --user=$DB_USER --password=$DB_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - '6379:6379'
    networks:
      - redis-net
    volumes:
      - redis-data:/data

  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - .env
    entrypoint: celery worker --workdir . -A PyMatcha.celery -B --loglevel=debug
    volumes:
      - pymatcha:/app
    depends_on:
      - redis
    links:
      - redis
    networks:
      - redis-net
      - mysql-net

  app:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:5000"
    volumes:
      - app:/app
    depends_on:
      - mysql
      - redis
      - worker
    links:
      - mysql
      - redis
      - worker
    networks:
      - redis-net
      - mysql-net

networks:
  redis-net:
  mysql-net:

volumes:
  redis-data:
  mysql:
  app:
